### PR TITLE
Fix click behavior on mobile devices

### PR DESCRIPTION
**Pull request by jmastr**

### CODE REVIEW

**Comment by kamalkhan** [comment]
Thank you.

**Comment by Nio-av** [comment]
See:
https://wordpress.org/support/topic/bug-report-on-first-hover-no-animation-not-clickable/

I also still have troubles. (iOS 12.1.4; but also in Lambda Test & virtual devices (iOS & Android). It is not possible to add Stars. But I'm not quite sure, wether this error caused of NGINX and Google Pagespeed Module or from the PlugIn. I'll test it on an other Server today.

@kamalkhan , Does the last update uploaded on WordPress.org includes the full merge?
@jmastr , is everything working for you? What is your Server Configuration?

**Comment by jmastr** [comment]
@Nio-av I can rate from a real iOS 12.4.1 device. However, the `js.min.js` was cached during my development, so I had to clear my Safari cache to get rid of the double clicking bug. I use a pretty standard Apache setup. You can try to rate something here from your iOS: https://www.veggi.es

**Comment by Nio-av** [comment]
I found my error: There was an other HTML-Element placed aboth the kk Star Rating Element. So, a small change of z-index fixed everything. Thanks for your Help.

**Pull request merged**
