### PR TITLE
replaced br clear with CSS clearfix

### PR DESCRIPTION
**Pull request by leecollings**
The clear attribute on the br element is obsolete. Replaced with CSS alternative.

### CODE REVIEW

**Comment by leecollings** [comment]
Fixed the warning notice for PHP 7

**Comment by kamalkhan** [comment]
Kindly clone the master branch and create a new pull request for the php 7 warning so I may merge the fix.

**Comment by leecollings** [comment]
I have, that's what this is... it's added this automatically to the existing pull request that I made last year, I don't think you've accepted that.

**Comment by kamalkhan** [comment]
I didnt merge the previous commit as I dont think adding a clearfix class will change anything because there is no clearfix css rule in the stylesheet. I am closing this PR so you may send a new pull request as I had to fix the indentation for the index.php file in the meantime.

**Pull request closed without merging**
