### PR TITLE
Correct schema.org for AggregateRating legend

### PR DESCRIPTION
**Pull request by manooweb**
Hi,

I use kk start ratings plugin on a website and snippet were not displayed in google search results.
When I corrected grs_legend function with new schema.org for AggregateRating schema, snippet is now displayed again.

https://schema.org/AggregateRating

**Note** : for working kk star ratings code must be embeded in another schema as Article ou Blog which aggregateRating is a property

https://schema.org/Article
https://schema.org/Blog

Best Regards
Emmanuel

### CODE REVIEW

**Comment by kamalkhan** [comment]
Hi, can you create a PR so that only the changes are reflected in the diff (https://github.com/kamalkhan/kk-star-ratings/pull/23/commits/4fd2165ce27494464700ed31288a5e3fb8070f94)

Currently the whole index.php file is being replaced in the github editor so I can not see the changes you have made.

Thank you.

**Comment by manooweb** [comment]
OK. I don't why all the index file is changed baecause I changed only some part of grs_legend function.

I will see if I can do another PR.

Thanks

**Comment by kamalkhan** [comment]
Still the same issue, It says 741 additions and 743 deletions :(

I will see how this can be cleaned up. Maybe adding a .editorconfig file.

**Comment by kamalkhan** [comment]
I have added a .editorconfig file so that the encoding is correct. Kindly fork the master branch into a non master branch, make the changes and send a new PR so I may merge the changes.

**Comment by manooweb** [comment]
I'm still looking for why. 

I use UTF-8 and PSR-2 formatting and netbeans.

I did some other PR without problem.

So, I delete autoformatting code, the diff with git is ok but when I push on githug it is not ok for PR :-/

I fork again your repository for testing and I will do another PR when it will ok.

**Comment by manooweb** [comment]
I saw .editorconfig file. You configured LF for line feed but index.php file is with CRLF linefeed.

I will do a new branch for testing and will do a PR on it.

Thanks

**Comment by manooweb** [comment]
Hi,

I am closing this PR because I did another one with correct code fomatting.

Best regards
Emmanuel

**Comment by kamalkhan** [comment]
Merged using https://github.com/kamalkhan/kk-star-ratings/pull/24

**Pull request closed without merging**
