### PR TITLE
fix: ajax json error

### PR DESCRIPTION
**Pull request by gbretas**
I have fixed an error that is listed in wordpress.org

https://wordpress.org/support/topic/add-rating-not-working/

https://wordpress.org/support/topic/i-cant-vote/

### CODE REVIEW

**Comment by kamalkhan** [comment]
I don't think the quotes is an issue. The double quotes in the attribute is already encoded.

**Comment by gbretas** [comment]
@kamalkhan this is the only thing that is causing the issue.

the payload have double quotes that is not encoded, and change to single quotes solved the problem. I have test, and you can check at diariomomento.com.br

**Comment by kamalkhan** [comment]
This is the output html. Please let me know if you find double quotes in the attribute value which needs to be escaped.

```
data-payload="{&quot;align&quot;:&quot;left&quot;,&quot;id&quot;:&quot;1&quot;,&quot;slug&quot;:&quot;default&quot;,&quot;valign&quot;:&quot;top&quot;,&quot;ignore&quot;:&quot;&quot;,&quot;reference&quot;:&quot;auto&quot;,&quot;class&quot;:&quot;&quot;,&quot;count&quot;:&quot;3&quot;,&quot;readonly&quot;:&quot;&quot;,&quot;score&quot;:&quot;4.7&quot;,&quot;best&quot;:&quot;5&quot;,&quot;gap&quot;:&quot;5&quot;,&quot;greet&quot;:&quot;Rate this post&quot;,&quot;legend&quot;:&quot;4.7\/5 - (3 votes)&quot;,&quot;size&quot;:&quot;24&quot;,&quot;width&quot;:&quot;133.8&quot;,&quot;_legend&quot;:&quot;{score}\/{best} - ({count} {votes})&quot;,&quot;font_factor&quot;:&quot;1.25&quot;}"
```

**Comment by gbretas** [comment]
I”ve test in WordPress 6.0.3 and it’s not escaping.
There is many people in Wordpress.org with this problem.

**Pull request merged**
